### ISSUE TITLE
Filters with sub-criteria for non-existent parameters crash test function

### ISSUE THREAD

**Issue by kav** [mirek/node-json-criteria#6]
Perhaps I'm holding it wrong, but I'm seeing an error if my filter has nesting that isn't present in the object under filter. I can preprocess to ensure keys match if this is the expected behavior but that seems a bit messy.

```javascript
import 'babel-polyfill';
import { test } from 'json-criteria';

console.log(test({ bar: 1 }, { foo: { baz: 1, bar: '1' } }))
```

Expected:
```console
false
```

Actual:
```
./node_modules/json-criteria/lib/engine.js:149
                r = r && this.test(dvp[dk[0]], qv);
                                      ^

TypeError: Cannot read property 'baz' of undefined
    at Engine.test (/Users/kav/Projects/_OS/test/node_modules/json-criteria/lib/src/engine.js:81:35)
    at Engine.test (/Users/kav/Projects/_OS/test/node_modules/json-criteria/lib/src/engine.js:81:27)
    at test (/Users/kav/Projects/_OS/test/node_modules/json-criteria/lib/src/index.js:8:17)
    at Object.<anonymous> (/Users/kav/Projects/_OS/test/index.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/Users/kav/Projects/_OS/test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kav/Projects/_OS/test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by kav** [comment]
Happy to PR a null check if you'd like

**Comment by mirek** [comment]
Yes, that doesn't look right, can you check if that commit fixes it (sorry, commit message closed this issue).

**Comment by kav** [comment]
Looks good to me but you've got one issue:
```javascript
  describe('implicit $eq', () => {
    n({ bar: 1 }, { foo: { baz: 1, bar: '1' } })
    ...
```
isn't actually running. you need an `it(`. Only noticed because I did the same but tried to fail the test first and didn't

**Comment by kav** [comment]
Looks good to me
